### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by lordmikefin** [christian-korneck/get_win8key#2]
Hi,
at first, thanks for great script.

It seems you have create this nice python script with python 2.7.x

I tried to run your script with python 3.4.2
but I just got punch of errors.

I made few changes and now it worked great with python 3.4.2

**Comment by lordmikefin** [comment]
Here is my changes:

29c29
< 	if str(table) in tables:
---
> 	if table in tables:
51c51
< 	table="MSDM"
---
> 	table=b"MSDM"
58c58
< 			return str(rawtable[56:len(rawtable)])
---
> 			return rawtable[56:len(rawtable)].decode("utf-8")
62c62
< 		print "[ERR] - ACPI table " + table + " not found on this system"
---
> 		print("[ERR] - ACPI table " + str(table) + " not found on this system")
68c68
< 		print "unexpected error"
---
> 		print("unexpected error")
71c71
< 		print str(WindowsKey)
---
> 		print(str(WindowsKey))
73c73
< 	print "unexpected error"
---
> 	print("unexpected error")

**Comment by christian-korneck** [comment]
hi lordmikefin,

thanks for that! Can you make a pull request with your changes?

Best,
Christian

**Comment by christian-korneck** [comment]
thanks, merged with your changes.
